server:
  port: 81
  servlet:
    context-path: /deslre

spring:
  application:
    name: SeparateBackend
  datasource:
    username: root
    password: 200381
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deslre?useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  neo4j:
    uri: bolt://192.168.1.26:7687
    authentication:
      username: neo4j
      password: 200381
